# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YZY_ qdaily' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YZY_ qdaily
   pod 'AFNetworking', '~> 3.1.0'
   pod 'Masonry', '~> 1.0.2'
end
